#pragma once

#include <molcpp/io/base/trajectory.hpp>
#include <molcpp/io/formats/xyz/reader.hpp>
#include <molcpp/io/formats/xyz/writer.hpp>
#include <molcpp/core/frame.hpp>
#include <molcpp/core/element.hpp>
#include <molcpp/types.hpp>
#include <filesystem>
#include <vector>
#include <memory>
#include <array>

namespace molcpp::io {

// 类型别名
using path_type = std::filesystem::path;

// =============================================================================
// XYZ 轨迹读写函数
// =============================================================================

/**
 * @brief Read XYZ trajectory file and return a trajectory reader.
 */
inline std::unique_ptr<XYZReader> read_xyz_trajectory(const path_type& path) { 
    return std::make_unique<XYZReader>(path); 
}

/**
 * @brief Write frames to an XYZ trajectory file.
 */
inline void write_xyz_trajectory(const path_type& path, const std::vector<Frame>& frames) { 
    XYZWriter writer(path); 
    for (const auto& frame : frames) {
        writer.write_frame(frame); 
    }
}

/**
 * @brief Write a single frame to an XYZ file.
 */
inline void write_xyz_frame(const path_type& path, const Frame& frame) { 
    XYZWriter writer(path); 
    writer.write_frame(frame); 
}

// =============================================================================
// 便捷函数
// =============================================================================

/**
 * @brief Create a simple XYZ file from coordinates and elements.
 */
inline void write_simple_xyz(const path_type& path,
                             const std::vector<std::string>& elements,
                             const std::vector<Vec3<Real>>& coordinates,
                             const std::string& comment = "Generated by MolCpp") {
    // Create a frame
    Frame frame;
    
    // Create atoms block
    Block atoms_block;
    
    size_t n_atoms = elements.size();
    
    // Set atomic numbers using Element class
    std::array<size_t, 1> element_shape = {n_atoms};
    RealArray element_array = xt::zeros<Real>(element_shape);
    for (size_t i = 0; i < n_atoms; ++i) {
        try {
            auto element_data = molcpp::Element::create(elements[i]);
            element_array(i) = static_cast<Real>(element_data.number);
        } catch (const std::exception&) {
            // Default to unknown element (X)
            element_array(i) = 0.0;
        }
    }
    atoms_block.set("atomic_numbers", element_array);
    
    // Set coordinates
    std::array<size_t, 2> coord_shape = {n_atoms, 3};
    CoordArray coord_array = xt::zeros<Real>(coord_shape);
    for (size_t i = 0; i < n_atoms; ++i) {
        for (int j = 0; j < 3; ++j) {
            coord_array(i, j) = coordinates[i](j);
        }
    }
    atoms_block.set("coordinates", coord_array);
    
    // Add atoms block to frame
    frame.set_block("atoms", std::move(atoms_block));
    
    // Set metadata
    frame.set_metadata("comment", comment);
    frame.set_metadata("n_atoms", static_cast<int>(n_atoms));
    
    // Write frame
    write_xyz_frame(path, frame);
}

} // namespace molcpp::io
