# fmt: off
# flake8: noqa
"""
This file declares the C-API corresponding to molcpp.h, in a way compatible
with the ctypes Python module.

This file is automatically generated by `python/scripts/gen-decl.py`,
do not edit it manually!
"""

import ctypes
import enum
import platform
from ctypes import CFUNCTYPE, POINTER


arch = platform.architecture()[0]
if arch == "32bit":
    c_uintptr_t = ctypes.c_uint32
elif arch == "64bit":
    c_uintptr_t = ctypes.c_uint64





def setup_functions(lib):
    # from .status import _check_status

    lib.molcpp_add.argtypes = [
        ctypes.c_int,
        ctypes.c_int,
    ]
    lib.molcpp_add.restype = ctypes.c_int

    lib.molcpp_multiply.argtypes = [
        ctypes.c_float,
        ctypes.c_float,
    ]
    lib.molcpp_multiply.restype = ctypes.c_float
